// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbBSSMUrNl8i4ZxkhjPOU4RE3V3AbdCIA',
    appId: '1:510149234919:web:acc75ce4017cc9014e5242',
    messagingSenderId: '510149234919',
    projectId: 'abast-control',
    authDomain: 'abast-control.firebaseapp.com',
    storageBucket: 'abast-control.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx8Bo9FnZGXYPHunBRWU8ptxYS1QM6ZR4',
    appId: '1:510149234919:android:62e468624f08fa994e5242',
    messagingSenderId: '510149234919',
    projectId: 'abast-control',
    storageBucket: 'abast-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVqtT40j0V5axwbUrcHjL2sDOWRsIQIj8',
    appId: '1:510149234919:ios:d0b5d959f044de194e5242',
    messagingSenderId: '510149234919',
    projectId: 'abast-control',
    storageBucket: 'abast-control.appspot.com',
    iosBundleId: 'com.example.abastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVqtT40j0V5axwbUrcHjL2sDOWRsIQIj8',
    appId: '1:510149234919:ios:d0b5d959f044de194e5242',
    messagingSenderId: '510149234919',
    projectId: 'abast-control',
    storageBucket: 'abast-control.appspot.com',
    iosBundleId: 'com.example.abastApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbBSSMUrNl8i4ZxkhjPOU4RE3V3AbdCIA',
    appId: '1:510149234919:web:bf7cdd2fa898c6b94e5242',
    messagingSenderId: '510149234919',
    projectId: 'abast-control',
    authDomain: 'abast-control.firebaseapp.com',
    storageBucket: 'abast-control.appspot.com',
  );

}